site_name: Terraform Framework Validators

theme:
  name: material
  palette:
    - scheme: orangeCorp
  features:
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - header.autohide
    - navigation.instant
  icon:
    repo: fontawesome/brands/github-alt
  favicon: https://opensource.orange.com/wp-content/themes/boosted/favicon.ico
  logo: https://boosted.orange.com/docs/5.3/assets/brand/orange-logo.svg

extra_css:
  - stylesheets/orange.css

nav:
  - Overview: "index.md"
  - How to use: "getting-started.md"
  - String: "stringvalidator/index.md"
  - Bool: "boolvalidator/index.md"
  - Int32: "int32validator/index.md"
  - Int64: "int64validator/index.md"
  - List: "listvalidator/index.md"
  - Set: "setvalidator/index.md"
  - Map: "mapvalidator/index.md"
  - Object: "objectvalidator/index.md"
  - â‡— Other projects: "https://orange-cloudavenue.github.io/projects"


plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/orange-cloudavenue/terraform-plugin-framework-validators
repo_name: orange-cloudavenue/terraform-plugin-framework-validators

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/orange-cloudavenue

copyright: Copyright &copy; Orange 2025
